# config/packages/api_platform.yaml
api_platform:
  title: "Horse Equipment Tracker API"
  description: "API for managing horse equipment reservations"
  version: "1.0.0"
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
