# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: api_login_check
        success_handler: app.authentication.jwt_success_handler
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
  # Define security rules here
  # Ask for good practices
  # - { path: ^/api/login, roles: PUBLIC_ACCESS } and register and documentation
  # - { path: ^/api, methods: [GET], roles: PUBLIC_ACCESS }  # Anyone can view anything
  # - { path: ^/api, methods: [POST, PUT, DELETE], roles: ROLE_ADMIN }  # Only admin can create, update, delete
