controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Admin Authentication Routes
admin_login:
  path: /admin/login
  controller: App\Controller\Admin\SecurityController::login
  methods: [GET, POST]

admin_logout:
  path: /admin/logout
  controller: App\Controller\Admin\SecurityController::logout

# Admin Dashboard Route
admin_dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

# Admin Equipment Routes
admin_equipment_index:
  path: /admin/equipment
  controller: App\Controller\Admin\EquipmentController::index

admin_equipment_new:
  path: /admin/equipment/new
  controller: App\Controller\Admin\EquipmentController::new
  methods: [GET, POST]

admin_equipment_edit:
  path: /admin/equipment/{id}/edit
  controller: App\Controller\Admin\EquipmentController::edit
  methods: [GET, POST]

admin_equipment_delete:
  path: /admin/equipment/{id}/delete
  controller: App\Controller\Admin\EquipmentController::delete
