security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    api:
      pattern: ^/api
      stateless: true
      anonymous: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - {
        path: ^/api,
        roles: IS_AUTHENTICATED_FULLY,
        methods: [POST, PUT, DELETE],
      }
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
