# config/packages/api_platform.yaml
api_platform:
  title: "Horse Equipment Tracker API"
  description: "API for managing horse equipment reservations"
  version: "1.0.0"
  # Modifs debut
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  # docs_formats:
  #   jsonld: ["application/ld+json"]
  #   jsonopenapi: ["application/vnd.openapi+json"]
  #   html: ["text/html"]
  # # Modifs fin
  # show_webby: false
  # swagger:
  #   api_keys:
  #     JWT:
  #       name: Authorization
  #       type: header
  # defaults:
  #   stateless: true
  #   cache_headers:
  #     vary: ["Content-Type", "Authorization", "Origin"]
  # enable_swagger_ui: true
  # enable_re_doc: true
