# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    admin:
      pattern: ^/admin
      provider: app_user_provider
      form_login:
        login_path: admin_login
        check_path: admin_login
        default_target_path: admin_dashboard
        username_parameter: _username
        password_parameter: _password
      logout:
        path: admin_logout
        target: admin_login

    main:
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_home
        username_parameter: _username
        password_parameter: _password
      logout:
        path: app_logout
        target: app_login

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: api_login_check
        success_handler: app.authentication.jwt_success_handler
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  access_control:
    # Admin section
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }

    # Public section
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }

    # API section
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
